create table if not exists public.callcenter_live_transcript_events (
  id bigint generated by default as identity primary key,
  call_sid text not null,
  transcription_sid text,
  sequence_id bigint,
  track text,
  speaker text,
  text text not null default '',
  is_final boolean not null default false,
  stability double precision,
  confidence double precision,
  occurred_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists callcenter_live_transcript_events_call_sid_idx
  on public.callcenter_live_transcript_events (call_sid, id);

alter table public.callcenter_live_transcript_events enable row level security;

drop policy if exists "Authenticated users can read live transcript events"
  on public.callcenter_live_transcript_events;

create policy "Authenticated users can read live transcript events"
  on public.callcenter_live_transcript_events
  for select
  to authenticated
  using (true);

do $$
begin
  alter publication supabase_realtime add table public.callcenter_live_transcript_events;
exception
  when duplicate_object then null;
end $$;
